//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.VsSolutionSort.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.VsSolutionSort.Resources.HelpResource", typeof(HelpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VsSolutionSort sorts the project entries in a Visual Studio solution file in the order as Visual Studio shows them in the Solution Explorer. Sorting the project entries in the solution file on changes helps users compare similar solution files, such as those often in revision control systems..
        /// </summary>
        internal static string Help100_Description {
            get {
                return ResourceManager.GetString("Help100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Help200_Usage {
            get {
                return ResourceManager.GetString("Help200_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VsSolutionSort.exe [options] &lt;input.sln&gt;.
        /// </summary>
        internal static string Help210_UsageInfo {
            get {
                return ResourceManager.GetString("Help210_UsageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Help300_Options {
            get {
                return ResourceManager.GetString("Help300_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}? | {1}help
        /// displays this help message.
        /// </summary>
        internal static string Help310_HelpOption {
            get {
                return ResourceManager.GetString("Help310_HelpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}v | {1}version
        /// displays the version of this program.
        /// </summary>
        internal static string Help311_VersionOption {
            get {
                return ResourceManager.GetString("Help311_VersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs Files:.
        /// </summary>
        internal static string Help400_Input {
            get {
                return ResourceManager.GetString("Help400_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;input.sln&gt; - a Visual Studio solution file..
        /// </summary>
        internal static string Help410_InputSolution {
            get {
                return ResourceManager.GetString("Help410_InputSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Codes:.
        /// </summary>
        internal static string Help800_ExitCodes {
            get {
                return ResourceManager.GetString("Help800_ExitCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exit codes show the success of the operation..
        /// </summary>
        internal static string Help801_ExitDescription {
            get {
                return ResourceManager.GetString("Help801_ExitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - The program ran successfully.
        /// </summary>
        internal static string Help810_Success {
            get {
                return ResourceManager.GetString("Help810_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - There was an error parsing the Visual Studio solution file.
        /// </summary>
        internal static string Help811_SolutionError {
            get {
                return ResourceManager.GetString("Help811_SolutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255 - There was an unknown error.
        /// </summary>
        internal static string Help899_UnknownError {
            get {
                return ResourceManager.GetString("Help899_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VsSolutionSort Version: {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VsSolutionSort Version: {0}; {1}..
        /// </summary>
        internal static string VersionCopyright {
            get {
                return ResourceManager.GetString("VersionCopyright", resourceCulture);
            }
        }
    }
}
